###############################################################################
# CLB + HTTPS listener (SNI mode) + target group (stages B/C)
#
# This version tests a stricter set of scenarios than the last one:
#
#   1. one certificate carrying 2 wildcard SANs (*.alpha / *.beta)
#   2. SNI mode — exactly where we got burned last time: with SniSwitch=true the
#      server ignores the main certificate_id, so the certificate must go through
#      multi_cert_info. This walks that correct path.
#   3. the listener has a real backend (a CVM), so end-to-end TLS can be verified
#      rather than just reading the API response.
#
# Flow: Terraform creates a self-signed placeholder cert and binds it to the
# listener -> seed it into the wecert state store -> wecert issues a real cert ->
# UpdateCertificateInstance rebinds -> curl the CLB VIP from inside the CVM to read
# the certificate actually being served.
###############################################################################

# Self-signed placeholder certificate. Generated by the tls provider at apply time;
# no private key file is ever written.
resource "tls_private_key" "placeholder" {
  count = var.create_clb ? 1 : 0

  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_self_signed_cert" "placeholder" {
  count = var.create_clb ? 1 : 0

  private_key_pem = tls_private_key.placeholder[0].private_key_pem

  subject {
    common_name  = var.clb_sni_domain
    organization = "wecert-test"
  }

  validity_period_hours = 720 # 30 days, enough for a whole test cycle
  early_renewal_hours   = 24

  allowed_uses = ["key_encipherment", "digital_signature", "server_auth"]
}

resource "tencentcloud_ssl_certificate" "placeholder" {
  count = var.create_clb ? 1 : 0

  name = "${var.name_prefix}-placeholder"
  # chomp is required: the tls provider's PEM ends with a newline, and the Tencent
  # Cloud API explicitly rejects a cert/key with a trailing newline
  # ("cert can't have \n suffix").
  cert = chomp(tls_self_signed_cert.placeholder[0].cert_pem)
  key  = chomp(tls_private_key.placeholder[0].private_key_pem)
  # SVR = server certificate (CA is for an issuing-authority certificate).
  type = "SVR"
  tags = local.tags
}

resource "tencentcloud_clb_instance" "test" {
  count = var.create_clb ? 1 : 0

  clb_name     = "${var.name_prefix}-clb"
  network_type = var.clb_network_type
  vpc_id       = tencentcloud_vpc.test[0].id

  # A public CLB cannot specify SubnetId (it fails with
  # "You can't specify parameter SubnetId when create open loadbalancer"),
  # while an internal one must.
  subnet_id = var.clb_network_type == "INTERNAL" ? tencentcloud_subnet.test[0].id : null

  # Only a public CLB needs bandwidth settings. Traffic-based billing at 1Mbps
  # costs almost nothing for testing.
  internet_charge_type       = var.clb_network_type == "OPEN" ? "TRAFFIC_POSTPAID_BY_HOUR" : null
  internet_bandwidth_max_out = var.clb_network_type == "OPEN" ? 1 : null

  tags = local.tags
}

resource "tencentcloud_clb_listener" "https" {
  count = var.create_clb ? 1 : 0

  clb_id        = tencentcloud_clb_instance.test[0].id
  listener_name = "${var.name_prefix}-https"
  protocol      = "HTTPS"
  port          = 443

  # ⚠️ The key point in SNI mode: the main certificate_id / certificate_ssl_mode
  # are **silently ignored** by the server, and the certificate must be configured
  # through multi_cert_info.
  #
  # This trap presents in a very misleading way: the listener is created, Terraform
  # state has a certificate_id, terraform plan reports "No changes" (the provider
  # does not read the binding back), and yet not a single certificate is actually
  # bound. The only thing that exposes it is UpdateCertificateInstance failing with
  # FailedOperation.CertificateDeployInstanceEmpty.
  sni_switch = true

  multi_cert_info {
    cert_id_list = [tencentcloud_ssl_certificate.placeholder[0].id]
    ssl_mode     = "UNIDIRECTIONAL"
  }

  # ⚠️ Certificate binding is wecert's business; Terraform must not touch it.
  #
  # Otherwise the two fight: Terraform treats certificate_id / multi_cert_info as
  # desired state and every apply flushes it back to the placeholder cert
  # configured here, while wecert changes that field out of band via
  # UpdateCertificateInstance. This was observed for real: after a few applies the
  # certificates on both rules had been quietly reverted to the placeholder, while
  # the wecert state store still believed the new certificate was deployed — the
  # two sides disagreed about reality.
  lifecycle {
    ignore_changes = [multi_cert_info, certificate_id, certificate_ssl_mode]
  }

  # Note: the CLB listener resource does not support tags; it is destroyed along
  # with the CLB.
}

# ── backend: one forwarding rule per domain, all attached to the same CVM ───
#
# HTTPS is a layer-7 listener, so forwarding rules are required to attach a
# backend; and Tencent Cloud does not allow a url-fallback default rule — every
# rule must carry a domain. So this is one rule per wildcard domain, with both
# rules attached to the same CVM.
#
# The classic tencentcloud_clb_attachment is used instead of a target group: the
# target group resource fails under the current account with
# "Current account do not support to create v1 target group".

resource "tencentcloud_clb_listener_rule" "wildcard" {
  count = var.create_clb && var.create_cvm ? length(var.clb_rule_domains) : 0

  clb_id      = tencentcloud_clb_instance.test[0].id
  listener_id = tencentcloud_clb_listener.https[0].listener_id

  domain = var.clb_rule_domains[count.index]
  url    = "/"

  # The certificate has to be bound to the **rule**, not only to the listener.
  # This is exactly how CLB implements SNI with multiple certificates: one rule per
  # domain, each rule carrying its own certificate. Without it, creating the rule
  # fails with "Lack of parameter Certificate or MultiCertInfo".
  certificate_id       = tencentcloud_ssl_certificate.placeholder[0].id
  certificate_ssl_mode = "UNIDIRECTIONAL"

  health_check_switch        = true
  health_check_type          = "HTTP"
  health_check_http_path     = "/"
  health_check_interval_time = 5
  health_check_time_out      = 2
  health_check_health_num    = 3
  health_check_unhealth_num  = 3
  # Note: do not set health_check_http_code — it is a bitmask (1..31), not an HTTP
  # status code, and 200 fails outright with "cannot be higher than 31".

  # Same as above: certificate binding is wecert's business; Terraform must not
  # overwrite it.
  lifecycle {
    ignore_changes = [certificate_id, certificate_ssl_mode, certificate_ca_id]
  }
}

resource "tencentcloud_clb_attachment" "wildcard" {
  count = var.create_clb && var.create_cvm ? length(var.clb_rule_domains) : 0

  clb_id      = tencentcloud_clb_instance.test[0].id
  listener_id = tencentcloud_clb_listener.https[0].listener_id
  rule_id     = tencentcloud_clb_listener_rule.wildcard[count.index].rule_id

  # Both rules attach the same CVM — the backend does not distinguish by domain.
  targets {
    instance_id = tencentcloud_instance.test[0].id
    port        = 80
    weight      = 10
  }
}

# ── CLB security group ──────────────────────────────────────────────────────
#
# A public CLB is open to the whole internet by default. Attaching a security group
# narrows it down to just your own machine.
#
# Note this governs traffic **reaching CLB 443**, which is a different thing from
# the backend CVM's security group: the latter governs CLB -> CVM health checks and
# forwarding.
#
# If the egress IP changes you lock yourself out; change clb_allowed_cidrs and
# re-apply to fix it.

resource "tencentcloud_security_group" "clb" {
  count = var.create_clb && length(var.clb_allowed_cidrs) > 0 ? 1 : 0

  name        = "${var.name_prefix}-clb-sg"
  description = "wecert e2e test - who may reach the public CLB"
  tags        = local.tags
}

resource "tencentcloud_security_group_rule_set" "clb" {
  count = var.create_clb && length(var.clb_allowed_cidrs) > 0 ? 1 : 0

  security_group_id = tencentcloud_security_group.clb[0].id

  dynamic "ingress" {
    for_each = var.clb_allowed_cidrs
    content {
      action      = "ACCEPT"
      cidr_block  = ingress.value
      protocol    = "TCP"
      port        = "443"
      description = "test access to HTTPS listener"
    }
  }

  # Egress is unrestricted: the CLB only receives traffic passively.
  egress {
    action      = "ACCEPT"
    cidr_block  = "0.0.0.0/0"
    protocol    = "ALL"
    port        = "ALL"
    description = "egress"
  }
}

resource "tencentcloud_clb_security_group_attachment" "clb" {
  count = var.create_clb && length(var.clb_allowed_cidrs) > 0 ? 1 : 0

  load_balancer_ids = [tencentcloud_clb_instance.test[0].id]
  security_group    = tencentcloud_security_group.clb[0].id
}
