package acme

import (
	"context"
	"strings"
	"testing"
	"time"

	"github.com/susunola/wecert/internal/ratelimit"
	"github.com/susunola/wecert/internal/state"
)

// A certificate a gate permanently refuses is re-downloaded on every pass for the order's
// whole TTL -- but it is ONE issuance at the CA, so the certificate budgets may be booked
// once, not once per pass.
//
// Before the dedup, the spend happened before the notAfter and key-match gates, and each
// pass that the gate refused spent CertsPerExactIdentifierSet and CertsPerRegisteredDomain
// again: five days of a stuck order drained the published remainder to zero while nothing
// new had been issued, on the one limit that has no override path.
func TestARejectedCertificateIsBookedOncePerCertificateURL(t *testing.T) {
	store, m, fake, cert := newAPITestHarness(t, []string{"example.com"})
	// A pinned clock: the bucket refills with wall-clock time, and this test counts tokens.
	m.SetNow(func() time.Time { return time.Date(2026, 9, 16, 12, 0, 0, 0, time.UTC) })

	// The order's key is generated by the flow; the CA hands back a certificate for a
	// DIFFERENT key, so the key-match gate refuses it -- permanently, for this order.
	key, err := GenerateKey(cert.KeyType)
	if err != nil {
		t.Fatal(err)
	}
	keyPEM, err := MarshalPrivateKeyPEM(key)
	if err != nil {
		t.Fatal(err)
	}
	fake.certPEM = selfSignedCertPEM(t, time.Now().Add(90*24*time.Hour), cert.Domains...)

	o := &state.Order{CertName: cert.Name, OrderURL: "https://ca.test/order/1", KeyPEM: keyPEM}
	order := terminalOrder("https://ca.test/order/1", "https://ca.test/finalize/1", "https://ca.test/cert/1")
	st := &state.CertState{Name: cert.Name}

	// Three passes re-download the same certificate; the gate refuses each time.
	for pass := 0; pass < 3; pass++ {
		err := m.download(context.Background(), cert, st, o, order, round{})
		if err == nil || !strings.Contains(err.Error(), "does not belong to the private key") {
			t.Fatalf("pass %d: the key mismatch must refuse the certificate, got %v", pass, err)
		}
	}

	exact, err := store.GetRateBucket(ratelimit.CertsPerExactIdentifierSet.Name, cert.DomainKey())
	if err != nil {
		t.Fatal(err)
	}
	if want := ratelimit.CertsPerExactIdentifierSet.Capacity - 1; exact.Tokens != want {
		t.Errorf("one issuance was booked %d times against the exact-set budget (tokens=%v, want %v)",
			int(ratelimit.CertsPerExactIdentifierSet.Capacity-exact.Tokens), exact.Tokens, want)
	}
	domain, err := store.GetRateBucket(ratelimit.CertsPerRegisteredDomain.Name, "example.com")
	if err != nil {
		t.Fatal(err)
	}
	if want := ratelimit.CertsPerRegisteredDomain.Capacity - 1; domain.Tokens != want {
		t.Errorf("one issuance was booked %d times against the registered-domain budget (tokens=%v, want %v)",
			int(ratelimit.CertsPerRegisteredDomain.Capacity-domain.Tokens), domain.Tokens, want)
	}

	// A genuinely different certificate (a new URL) is a new issuance and must be booked again.
	order.Certificate = "https://ca.test/cert/2"
	if err := m.download(context.Background(), cert, st, o, order, round{}); err == nil {
		t.Fatal("the key mismatch still refuses the second certificate")
	}
	exact, err = store.GetRateBucket(ratelimit.CertsPerExactIdentifierSet.Name, cert.DomainKey())
	if err != nil {
		t.Fatal(err)
	}
	if want := ratelimit.CertsPerExactIdentifierSet.Capacity - 2; exact.Tokens != want {
		t.Errorf("a second certificate URL is a second issuance: tokens=%v, want %v", exact.Tokens, want)
	}
}
