#!/usr/bin/env python3
"""Render the six SVGs in docs/certificate-lifecycle.html to PNG.

Why a script instead of a one-off manual export: PNGs are binary, so they do not
follow along when the code changes. With a re-runnable command, a stale diagram is
only one `make diagrams` away from being fixed; without one it will inevitably rot,
and nobody will notice.

Why Chrome instead of rsvg-convert: every label on these diagrams lives inside a
<foreignObject> (the only way to make text actually wrap — SVG's <text> does not
wrap on its own). librsvg drops foreignObject entirely, so you get six blank
images.

Usage:
    python3 scripts/render-diagrams.py                # re-render both languages
    python3 scripts/render-diagrams.py --only 1       # render diagram 1 only
    python3 scripts/render-diagrams.py --lang en      # render English only
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "docs" / "diagrams"

# One set of diagrams per language. The Chinese version is the hand-written source
# of truth; the English version is generated by scripts/build-diagram-langs.py.
LANGS = [
    ("zh", ROOT / "docs" / "certificate-lifecycle.html"),
    ("en", ROOT / "docs" / "certificate-lifecycle.en.html"),
]

# File name of each diagram and the SVG index it corresponds to (1-based). The
# names are there to be referenced from the readme, so they are made
# self-explanatory rather than diagram-1/2/3.
NAMES = [
    "00-deployment-shape",
    "01-system-map",
    "02-intent-to-contract",
    "03-reconcile-decisions",
    "04-order-state-machine",
    "05-dns01-sequence",
    "06-certificate-lifetime",
]

CHROME_CANDIDATES = [
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Chromium.app/Contents/MacOS/Chromium",
    "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
    "google-chrome",
    "chromium",
    "chromium-browser",
]

# 2x images. GitHub scales wide images down to the container width, and a 1x image
# looks blurry on a retina display.
SCALE = 2

# Background color for the render, matching the .scroll card background in the HTML.
#
# It cannot be transparent: GitHub has a dark theme, and dark text over a
# transparent background turns into an unreadable smear.
BACKGROUND = "#f6f5f1"


def find_chrome() -> str:
    for c in CHROME_CANDIDATES:
        if os.path.sep in c:
            if os.access(c, os.X_OK):
                return c
        elif shutil.which(c):
            return shutil.which(c)
    sys.exit(
        "Chrome / Chromium / Edge not found. These diagrams must be rendered in a real browser —\n"
        "every label lives in a <foreignObject>, which converters like librsvg drop entirely."
    )


def extract_style(html: str) -> str:
    """Extract the contents of <style>.

    The whole block is copied rather than filtered down to the SVG-relevant rules:
    the extra body/table rules match nothing in an SVG document and are harmless,
    whereas missing one rule is a silent loss of styling.
    """
    m = re.search(r"<style>(.*?)</style>", html, re.S)
    if not m:
        sys.exit("no <style> block found in the source file")
    return m.group(1)


def extract_svgs(html: str) -> list[str]:
    return re.findall(r"<svg\b.*?</svg>", html, re.S)


def standalone(svg: str, css: str, index: int) -> str:
    """Wrap an <svg> fragment into an SVG document that can be opened standalone."""
    vb = re.search(r'viewBox="([\d.]+) ([\d.]+) ([\d.]+) ([\d.]+)"', svg)
    if not vb:
        sys.exit(f"diagram {index} has no viewBox, so its size cannot be determined")
    _, _, w, h = (float(x) for x in vb.groups())
    w, h = int(w), int(h)

    # The variables are attached to both :root and svg: when opened standalone
    # :root *is* the <svg>, but writing both explicitly makes the rules work in
    # both cases, referenced from an <img> and opened directly.
    vars_only = re.search(r":root\s*\{(.*?)\}", css, re.S)
    variables = vars_only.group(1) if vars_only else ""

    # The original viewBox is replaced by explicit dimensions: Chrome lays the
    # document out at this size when it opens it directly, which together with
    # --window-size fills the window exactly and leaves no blank margin.
    body = svg[svg.index(">") + 1 : svg.rindex("</svg>")]

    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'xmlns:xhtml="http://www.w3.org/1999/xhtml" '
        f'width="{w}" height="{h}" viewBox="0 0 {w} {h}">\n'
        f"<style>\n:root{{{variables}}}\nsvg{{{variables}}}\n{css}\n</style>\n"
        f'<rect x="0" y="0" width="{w}" height="{h}" fill="{BACKGROUND}"/>\n'
        f"{body}\n</svg>\n"
    )


def render(chrome: str, svg_path: Path, png_path: Path, w: int, h: int) -> None:
    cmd = [
        chrome,
        "--headless",
        "--disable-gpu",
        "--hide-scrollbars",
        "--no-sandbox",
        "--force-device-scale-factor=%d" % SCALE,
        "--window-size=%d,%d" % (w, h),
        "--screenshot=%s" % png_path,
        svg_path.as_uri(),
    ]
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    if not png_path.exists():
        sys.exit(f"failed to render {svg_path.name}:\n{res.stdout}\n{res.stderr}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", type=int, help="render diagram N only (1-based)")
    ap.add_argument("--lang", choices=[l for l, _ in LANGS], help="render one language only")
    args = ap.parse_args()

    chrome = find_chrome()

    with tempfile.TemporaryDirectory() as tmp:
        for lang, source in LANGS:
            if args.lang and lang != args.lang:
                continue
            if not source.exists():
                sys.exit(f"{source} not found (run scripts/build-diagram-langs.py to build the English page first)")

            html = source.read_text(encoding="utf-8")
            css = extract_style(html)
            svgs = extract_svgs(html)

            if len(svgs) != len(NAMES):
                sys.exit(f"{source.name} has {len(svgs)} diagrams, the script expects {len(NAMES)}"
                         f" — remember to keep NAMES in sync when adding or removing a diagram")

            out_dir = OUT_DIR / lang
            out_dir.mkdir(parents=True, exist_ok=True)
            print(f"{lang}: {source.name}")

            for i, svg in enumerate(svgs, start=1):
                if args.only and i != args.only:
                    continue

                name = NAMES[i - 1]
                vb = re.search(r'viewBox="[\d.]+ [\d.]+ ([\d.]+) ([\d.]+)"', svg)
                w, h = int(float(vb.group(1))), int(float(vb.group(2)))

                svg_path = Path(tmp) / f"{lang}-{name}.svg"
                doc = standalone(svg, css, i)

                # A standalone SVG is parsed by the browser as **XML**, and what
                # HTML permits is not necessarily legal XML — the classic case is
                # `<br>`: fine in HTML, but in SVG it turns the whole diagram into a
                # Chrome error page, and the render still "succeeds", just producing
                # an image with the error text on it. So validate here first.
                try:
                    ET.fromstring(doc)
                except ET.ParseError as e:
                    sys.exit(f"✗ {lang}/{name}: the generated SVG is not valid XML ({e}).\n"
                             f"  It is most likely an HTML-only shorthand in the source,"
                             f" such as <br> instead of <br/>.")
                svg_path.write_text(doc, encoding="utf-8")

                png_path = out_dir / f"{name}.png"
                render(chrome, svg_path, png_path, w, h)

                kb = png_path.stat().st_size / 1024
                print(f"  {name}.png  {w}x{h} @{SCALE}x  {kb:.0f} KB")

    print(f"\nwrote {OUT_DIR.relative_to(ROOT)}/{{zh,en}}/")


if __name__ == "__main__":
    main()
