package spec

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/susunola/wecert/internal/atomicfile"
	"github.com/susunola/wecert/internal/config"
	"github.com/susunola/wecert/internal/group"
)

// Document envelope. These two fields are not decoration: they turn "wrong file"
// into a clear error instead of unrelated YAML silently parsed as desired state.
const (
	APIVersionV1     = "wecert/v1"
	KindDesiredState = "DesiredState"
)

// DocumentHeader is written at the very top of a generated document.
//
// The document is a **derived artifact**: hand edits are overwritten by the next
// onboarding run. Saying so on the first line of the file is far more useful
// than saying it only in the README.
const DocumentHeader = `# This file is generated by wecert-onboard; do not edit it by hand.
# It is a contract: wecert only reads it and never infers anything.
# To change the desired state, change the upstream declaration (the _wecert DNS
# record / onboarding config) and re-run wecert-onboard; hand edits are overwritten.
`

// Document is the contract between the onboarding component and wecert.
type Document struct {
	APIVersion string `yaml:"apiVersion" json:"apiVersion"`
	Kind       string `yaml:"kind" json:"kind"`

	// GeneratedAt is the write time. wecert uses it to judge whether the document
	// is already too old (too old means the onboarding component is dead, and that
	// alone deserves an alert).
	GeneratedAt time.Time `yaml:"generatedAt" json:"generatedAt"`

	// Generator records who wrote it and at which version, to trace back
	// "why did we issue an extra certificate last Tuesday".
	Generator string `yaml:"generator" json:"generator"`

	// Revision is the fingerprint of Certificates, from the same source as
	// Result.Revision.
	Revision string `yaml:"revision" json:"revision"`

	Certificates []config.Certificate `yaml:"certificates" json:"certificates"`
}

// Revision is a fingerprint of the desired-state content.
//
// It covers only the certificates and deliberately **excludes** GeneratedAt and
// Revision itself: otherwise it would change on every onboarding run, and "did
// the desired state actually change?" -- the most basic question -- would be
// unanswerable. Certificates are sorted by name and domains are sorted first, so
// neither kind of ordering is misread as change.
func Revision(certs []config.Certificate) string {
	// Hash a name-sorted copy: the same certificate set in a different order is the
	// same desired state, and the generator's grouping order is not semantic.
	ordered := append([]config.Certificate(nil), certs...)
	sort.Slice(ordered, func(i, j int) bool { return ordered[i].Name < ordered[j].Name })

	h := sha256.New()
	for _, c := range ordered {
		fmt.Fprintf(h, "name=%s\nprofile=%s\nkeyType=%s\nrenewBefore=%s\ndeploy=%t\n",
			c.Name, c.Profile, c.KeyType, c.RenewBefore, c.Deploy.Enabled)

		domains := append([]string(nil), c.Domains...)
		sort.Strings(domains)
		for _, d := range domains {
			fmt.Fprintf(h, "domain=%s\n", d)
		}
		h.Write([]byte{0})
	}
	return "sha256:" + hex.EncodeToString(h.Sum(nil))[:16]
}

// LoadDocument reads and validates a desired-state document.
//
// Validation is stricter than for the configuration file because this document
// is machine-written: if a machine-written file is malformed, the upstream logic
// has a bug, and **rejecting** is far safer than "best effort".
func LoadDocument(path string) (*Document, error) {
	// The document *is* the desired state: whoever can rewrite it decides which
	// domains get served and which quietly stop being renewed. Two things follow.
	//
	// A symlink is refused rather than followed, so the configured path cannot be
	// redirected at whatever the writer chooses. And a group- or world-writable file
	// is refused, because on the default layout the document lives in a 0700 state
	// directory and nothing but the daemon's own account has any business writing it.
	//
	// Readability is deliberately not checked: the file is 0644 so an operator can
	// inspect it, and only the *write* bits can change what it says.
	//
	// The checks below run against the file that is actually READ, not against a path
	// inspected a moment earlier. os.Open + f.Stat closes two holes at once: a symlink
	// swapped in between the check and the read is no longer followed (O_NOFOLLOW where
	// the platform has it), and the mode/owner being validated are the ones on the open
	// descriptor rather than on whatever the name resolves to now.
	f, err := openDocumentFile(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	fi, err := f.Stat()
	if err != nil {
		return nil, fmt.Errorf("stat desired-state document %s: %w", path, err)
	}
	if !fi.Mode().IsRegular() {
		return nil, fmt.Errorf("the desired-state document %s is not a regular file", path)
	}
	if perm := fi.Mode().Perm(); perm&0o022 != 0 {
		return nil, fmt.Errorf("the desired-state document %s is group- or world-writable (%04o); anyone who can write it can change which domains are served", path, perm)
	}
	// Ownership is the other half of "nothing but the daemon's account may write this":
	// the mode bits say nothing about WHO the writer is, so a 0644 document owned by a
	// different local user passes the check above and can be rewritten at will.
	if err := checkDocumentOwner(path, fi); err != nil {
		return nil, err
	}
	// And the parent directory decides who may replace the file, since the writer
	// installs it by rename (see WriteDocument). A 0644 document in a 0777 directory is
	// world-writable in every sense that matters.
	if err := checkDocumentDir(path); err != nil {
		return nil, err
	}

	data, err := io.ReadAll(io.LimitReader(f, maxDocumentBytes+1))
	if err != nil {
		return nil, fmt.Errorf("read desired-state document: %w", err)
	}
	if len(data) > maxDocumentBytes {
		return nil, fmt.Errorf("desired-state document %s is larger than %d bytes: refusing a "+
			"truncated read, because a cut that lands on a certificate boundary parses as a complete "+
			"document and would silently drop the rest of the fleet", path, maxDocumentBytes)
	}

	doc := &Document{}
	dec := yaml.NewDecoder(bytes.NewReader(data))
	// Unknown fields are a hard error: the document is a contract, so a
	// misspelled field must blow up rather than be silently ignored -- an ignored
	// deploy field issues a certificate that is never deployed, and says nothing.
	dec.KnownFields(true)
	if err := dec.Decode(doc); err != nil {
		return nil, fmt.Errorf("parse desired-state document %s: %w", path, err)
	}
	if err := config.RejectExtraDocuments(dec, path); err != nil {
		return nil, err
	}

	if err := doc.Validate(); err != nil {
		return nil, fmt.Errorf("desired-state document %s: %w", path, err)
	}
	return doc, nil
}

// maxGeneratedAtSkew is how far in the future generatedAt may be before Validate rejects the
// document.
//
// The property being protected: a future-dated document must not be able to hide its own
// staleness. The alarm is "age > maxStaleness" (48h by default), so any tolerance well under
// that keeps the alarm meaningful -- once the clock catches up, real age exceeds the
// threshold and the alarm fires.
//
// The value is an hour rather than a few minutes, and that is the whole point of this
// comment. A tolerance tight enough to reject ordinary clock movement is not a safety
// feature, it is an outage: a corrected RTC or a VM snapshot restore steps the clock
// backwards, the document the generator just wrote then looks future-dated, and a rejected
// document is not a warning -- in enforce mode the daemon refuses to start and
// wecert-onboard refuses its round, so both halves stop at once and the cause looks exactly
// like a corrupt file. An hour absorbs every realistic correction while still refusing the
// "a day ahead" case that would silence the alarm.
const maxGeneratedAtSkew = time.Hour

// maxDocumentBytes bounds a document read. A desired-state document for even a few
// thousand names is far below this; the cap is here so a runaway generator cannot make
// the daemon allocate without limit.
//
// The cap is enforced by reading one byte past it, not by truncating: a LimitReader silently cut
// an oversized document, and a cut that happens to land on a certificate boundary parses as a
// complete YAML document -- measured with 114,909 of 200,000 certificates, accepted as the desired
// state. Acting on that strips the rest of the fleet from every certificate.
const maxDocumentBytes = 16 << 20

// openDocumentFile opens the document for reading, refusing to follow a symlink
// where the platform supports it. The flags are platform-specific -- see
// openflags_unix.go / openflags_other.go: O_NOFOLLOW and O_NONBLOCK do not exist
// everywhere, and platforms without them get a plain read-only open (the mode-bit
// checks in LoadDocument still apply there).
func openDocumentFile(path string) (*os.File, error) {
	f, err := os.OpenFile(path, documentOpenFlags, 0)
	if err != nil {
		if isSymlinkRefusal(err) {
			return nil, fmt.Errorf("the desired-state document %s is a symlink; refusing to follow it -- point the config at the real file", path)
		}
		return nil, fmt.Errorf("open desired-state document %s: %w", path, err)
	}
	return f, nil
}

// checkDocumentOwner requires the document to be owned by the account running wecert.
//
// On platforms without POSIX ownership the check is skipped: the alternative is refusing
// to run at all, and the mode-bit checks above still apply.
func checkDocumentOwner(path string, fi os.FileInfo) error {
	uid, ok := fileOwnerUID(fi)
	if !ok {
		return nil
	}
	if uid != uint32(os.Geteuid()) {
		return fmt.Errorf(
			"the desired-state document %s is owned by uid %d but wecert runs as uid %d; "+
				"whoever owns the file can rewrite which domains are served",
			path, uid, os.Geteuid())
	}
	return nil
}

// checkDocumentDir rejects a document whose parent directory is group- or world-writable.
//
// WriteDocument installs the file by rename, so the directory's permissions -- not the
// file's -- are what decide whether someone else can replace its contents with their own.
func checkDocumentDir(path string) error {
	dir := filepath.Dir(path)
	fi, err := os.Stat(dir)
	if err != nil {
		return fmt.Errorf("stat the desired-state document's directory %s: %w", dir, err)
	}
	if perm := fi.Mode().Perm(); perm&0o022 != 0 {
		return fmt.Errorf(
			"the directory holding the desired-state document (%s) is group- or world-writable (%04o); "+
				"anyone who can write it can replace the document, which decides which domains are served",
			dir, perm)
	}
	return nil
}

// Validate checks the document envelope, the certificate list and Name stability.
func (d *Document) Validate() error {
	if d.APIVersion != APIVersionV1 {
		return fmt.Errorf("apiVersion must be %q, got %q", APIVersionV1, d.APIVersion)
	}
	if d.Kind != KindDesiredState {
		return fmt.Errorf("kind must be %q, got %q", KindDesiredState, d.Kind)
	}
	if d.GeneratedAt.IsZero() {
		return errors.New("generatedAt is required: without it there is no way to tell a fresh document from one the onboarding component stopped updating weeks ago")
	}
	// A future timestamp is not a harmless clock skew: the staleness alarm is
	// "time.Since(generatedAt) > maxStaleness", so a date far enough ahead makes that
	// comparison false indefinitely. It is the one signal this architecture has for "the
	// onboarding component died and no new name will ever be picked up", and a
	// machine-written field that a human can edit must not be able to switch it off
	// silently -- especially since Revision deliberately covers only the certificates, so
	// changing generatedAt alone trips no other check.
	//
	// The tolerance is therefore derived from the staleness threshold rather than being a
	// small fixed number. A tight limit (this used to be 15 minutes) turns an ordinary NTP
	// correction or a VM snapshot restore into a rejected document, and a rejected document
	// is not a warning: the daemon refuses to start in enforce mode, and wecert-onboard
	// refuses its round, so both halves of the system stop at once -- a multi-day outage
	// from a clock step, with no way to distinguish it from a genuinely corrupt file.
	//
	// The invariant worth keeping is the one above: the document must not be able to hide
	// its own staleness. Tolerating up to `limit` of future skew does that, because the
	// alarm still fires once the clock catches up and real age exceeds maxStaleness.
	if skew := time.Until(d.GeneratedAt); skew > maxGeneratedAtSkew {
		return fmt.Errorf(
			"generatedAt (%s) is %s in the future; that is far enough ahead to hide the document "+
				"staleness alarm, so it is rejected (allow at most %s)",
			d.GeneratedAt.UTC().Format(time.RFC3339), skew.Round(time.Minute), maxGeneratedAtSkew)
	}

	// An empty document is always rejected.
	//
	// A "legitimately empty" file and a "generation failed, hence empty" file look
	// identical, and accepting the latter strips every domain from every
	// certificate. That risk is too asymmetric to leave a hole for "I really do
	// want to clear everything" -- that job belongs to an explicit, loud human act.
	if len(d.Certificates) == 0 {
		return errors.New("certificates is empty: an empty desired state is indistinguishable from a failed generation, and acting on it would strip every name from every certificate")
	}

	// Share one entry point with static config so the two paths cannot disagree
	// on strictness.
	if err := config.NormalizeCertificates(d.Certificates); err != nil {
		return err
	}

	for i := range d.Certificates {
		if err := checkNameStability(&d.Certificates[i]); err != nil {
			return err
		}
	}

	want := Revision(d.Certificates)
	if d.Revision == "" {
		d.Revision = want
	} else if d.Revision != want {
		return fmt.Errorf("revision %q does not match the certificates it describes (computed %q); "+
			"the file was most likely edited by hand or written by a different generator", d.Revision, want)
	}
	return nil
}

// checkNameStability pins down Name stability.
//
// A certificate name must derive from the grouping key, not from the domain set.
// Once that breaks, adding one domain conjures a brand-new record in the state
// store, and the old record's order URL, ARI certID and deployed CertID all
// become orphans -- "at most one in-flight order per certificate" stops holding,
// both orders fly at once, and they run straight into the exact-set rate limit
// (5 / 7 days, no override).
//
// The check sits on the contract boundary because this is the only place that
// can stop it: by the time wecert reads the state, the orphans already exist.
func checkNameStability(c *config.Certificate) error {
	regs := make(map[string]bool, 1)
	for _, d := range c.Domains {
		if reg := group.RegisteredDomain(d); reg != "" {
			regs[reg] = true
		}
	}
	if len(regs) == 0 {
		return fmt.Errorf("certificate %q: no domain has a registered domain", c.Name)
	}
	if len(regs) > 1 {
		// Crossing registered domains means an uncontrolled blast radius, and LE
		// quota is counted per registered domain anyway, so bundling them into one
		// certificate only makes "who dragged down whom" impossible to explain.
		names := make([]string, 0, len(regs))
		for r := range regs {
			names = append(names, r)
		}
		sort.Strings(names)
		return fmt.Errorf("certificate %q spans %d registered domains (%s): "+
			"every name in one certificate lives and dies together, and Let's Encrypt counts quota per registered domain, "+
			"so one certificate must stay inside one registered domain",
			c.Name, len(regs), strings.Join(names, ", "))
	}

	var reg string
	for r := range regs {
		reg = r
	}
	if want := group.CertName(reg); c.Name != want {
		return fmt.Errorf("certificate name %q is not stable for its domains: they all belong to %q, "+
			"so the name must be %q; a name that follows the domain set orphans the order URL, "+
			"ARI certID and deployed CertID every time a domain is added or removed",
			c.Name, reg, want)
	}
	return nil
}

// WriteDocument writes the document atomically.
//
// It must write a temp file in the same directory and then rename: wecert may be
// reading at that very moment, and a truncated document looks like "half the
// domains are gone" -- the most dangerous input there is. rename is atomic within
// one filesystem, so a reader sees either the old version or the new one.
func WriteDocument(path string, doc *Document) error {
	if err := doc.Validate(); err != nil {
		return err
	}
	return WriteDocumentUnchecked(path, doc)
}

// WriteDocumentUnchecked is WriteDocument without validation.
//
// It has exactly one caller: WriteDocument, which validates first and then delegates
// the write. A frozen onboarding round does NOT come through here: onboarding's Commit
// writes only the report in that case, so the document on disk stays at the previous
// revision -- generatedAt is not refreshed, and a freeze that outlasts
// desiredState.maxStaleness fires the staleness alarm. That is deliberate: a frozen
// round has no trustworthy conclusion to publish, and refreshing the timestamp would
// hide exactly the "the generator is stuck" condition the alarm exists to catch.
//
// Kept as a separate function so the write path (atomic temp file, fsync, rename) has
// a single implementation. Do not use it to bypass validation.
func WriteDocumentUnchecked(path string, doc *Document) error {
	body, err := yaml.Marshal(doc)
	if err != nil {
		return fmt.Errorf("encode desired-state document: %w", err)
	}

	// 0644: the document is read by the enforcement half of the deployment and by humans, and it
	// holds no secrets -- but it does decide which names are served, which is why the reader
	// refuses a group- or world-writable one and why the shared writer installs it by rename.
	//
	// The protocol (temp file in the same directory, fsync, permissions before the rename, rename,
	// sync the directory) lives in internal/atomicfile: this writer, the onboarding report and the
	// onboarding state file each grew their own copy and they had already drifted.
	return atomicfile.Write(path, append([]byte(DocumentHeader), body...), 0o644)
}
