package spec

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/susunola/wecert/internal/config"
	"github.com/susunola/wecert/internal/group"
)

// Document envelope. These two fields are not decoration: they turn "wrong file"
// into a clear error instead of unrelated YAML silently parsed as desired state.
const (
	APIVersionV1     = "wecert/v1"
	KindDesiredState = "DesiredState"
)

// DocumentHeader is written at the very top of a generated document.
//
// The document is a **derived artifact**: hand edits are overwritten by the next
// onboarding run. Saying so on the first line of the file is far more useful
// than saying it only in the README.
const DocumentHeader = `# This file is generated by wecert-onboard; do not edit it by hand.
# It is a contract: wecert only reads it and never infers anything.
# To change the desired state, change the upstream declaration (the _wecert DNS
# record / onboarding config) and re-run wecert-onboard; hand edits are overwritten.
`

// Document is the contract between the onboarding component and wecert.
type Document struct {
	APIVersion string `yaml:"apiVersion" json:"apiVersion"`
	Kind       string `yaml:"kind" json:"kind"`

	// GeneratedAt is the write time. wecert uses it to judge whether the document
	// is already too old (too old means the onboarding component is dead, and that
	// alone deserves an alert).
	GeneratedAt time.Time `yaml:"generatedAt" json:"generatedAt"`

	// Generator records who wrote it and at which version, to trace back
	// "why did we issue an extra certificate last Tuesday".
	Generator string `yaml:"generator" json:"generator"`

	// Revision is the fingerprint of Certificates, from the same source as
	// Result.Revision.
	Revision string `yaml:"revision" json:"revision"`

	Certificates []config.Certificate `yaml:"certificates" json:"certificates"`
}

// Revision is a fingerprint of the desired-state content.
//
// It covers only the certificates and deliberately **excludes** GeneratedAt and
// Revision itself: otherwise it would change on every onboarding run, and "did
// the desired state actually change?" -- the most basic question -- would be
// unanswerable. Domains are sorted first so ordering is not misread as change.
func Revision(certs []config.Certificate) string {
	h := sha256.New()
	for _, c := range certs {
		fmt.Fprintf(h, "name=%s\nprofile=%s\nkeyType=%s\nrenewBefore=%s\ndeploy=%t\n",
			c.Name, c.Profile, c.KeyType, c.RenewBefore, c.Deploy.Enabled)

		domains := append([]string(nil), c.Domains...)
		sort.Strings(domains)
		for _, d := range domains {
			fmt.Fprintf(h, "domain=%s\n", d)
		}
		h.Write([]byte{0})
	}
	return "sha256:" + hex.EncodeToString(h.Sum(nil))[:16]
}

// LoadDocument reads and validates a desired-state document.
//
// Validation is stricter than for the configuration file because this document
// is machine-written: if a machine-written file is malformed, the upstream logic
// has a bug, and **rejecting** is far safer than "best effort".
func LoadDocument(path string) (*Document, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read desired-state document: %w", err)
	}

	doc := &Document{}
	dec := yaml.NewDecoder(bytes.NewReader(data))
	// Unknown fields are a hard error: the document is a contract, so a
	// misspelled field must blow up rather than be silently ignored -- an ignored
	// deploy field issues a certificate that is never deployed, and says nothing.
	dec.KnownFields(true)
	if err := dec.Decode(doc); err != nil {
		return nil, fmt.Errorf("parse desired-state document %s: %w", path, err)
	}

	if err := doc.Validate(); err != nil {
		return nil, fmt.Errorf("desired-state document %s: %w", path, err)
	}
	return doc, nil
}

// Validate checks the document envelope, the certificate list and Name stability.
func (d *Document) Validate() error {
	if d.APIVersion != APIVersionV1 {
		return fmt.Errorf("apiVersion must be %q, got %q", APIVersionV1, d.APIVersion)
	}
	if d.Kind != KindDesiredState {
		return fmt.Errorf("kind must be %q, got %q", KindDesiredState, d.Kind)
	}
	if d.GeneratedAt.IsZero() {
		return errors.New("generatedAt is required: without it there is no way to tell a fresh document from one the onboarding component stopped updating weeks ago")
	}

	// An empty document is always rejected.
	//
	// A "legitimately empty" file and a "generation failed, hence empty" file look
	// identical, and accepting the latter strips every domain from every
	// certificate. That risk is too asymmetric to leave a hole for "I really do
	// want to clear everything" -- that job belongs to an explicit, loud human act.
	if len(d.Certificates) == 0 {
		return errors.New("certificates is empty: an empty desired state is indistinguishable from a failed generation, and acting on it would strip every name from every certificate")
	}

	// Share one entry point with static config so the two paths cannot disagree
	// on strictness.
	if err := config.NormalizeCertificates(d.Certificates); err != nil {
		return err
	}

	for i := range d.Certificates {
		if err := checkNameStability(&d.Certificates[i]); err != nil {
			return err
		}
	}

	want := Revision(d.Certificates)
	if d.Revision == "" {
		d.Revision = want
	} else if d.Revision != want {
		return fmt.Errorf("revision %q does not match the certificates it describes (computed %q); "+
			"the file was most likely edited by hand or written by a different generator", d.Revision, want)
	}
	return nil
}

// checkNameStability pins down Name stability.
//
// A certificate name must derive from the grouping key, not from the domain set.
// Once that breaks, adding one domain conjures a brand-new record in the state
// store, and the old record's order URL, ARI certID and deployed CertID all
// become orphans -- "at most one in-flight order per certificate" stops holding,
// both orders fly at once, and they run straight into the exact-set rate limit
// (5 / 7 days, no override).
//
// The check sits on the contract boundary because this is the only place that
// can stop it: by the time wecert reads the state, the orphans already exist.
func checkNameStability(c *config.Certificate) error {
	regs := make(map[string]bool, 1)
	for _, d := range c.Domains {
		if reg := group.RegisteredDomain(d); reg != "" {
			regs[reg] = true
		}
	}
	if len(regs) == 0 {
		return fmt.Errorf("certificate %q: no domain has a registered domain", c.Name)
	}
	if len(regs) > 1 {
		// Crossing registered domains means an uncontrolled blast radius, and LE
		// quota is counted per registered domain anyway, so bundling them into one
		// certificate only makes "who dragged down whom" impossible to explain.
		names := make([]string, 0, len(regs))
		for r := range regs {
			names = append(names, r)
		}
		sort.Strings(names)
		return fmt.Errorf("certificate %q spans %d registered domains (%s): "+
			"every name in one certificate lives and dies together, and Let's Encrypt counts quota per registered domain, "+
			"so one certificate must stay inside one registered domain",
			c.Name, len(regs), strings.Join(names, ", "))
	}

	var reg string
	for r := range regs {
		reg = r
	}
	if want := group.CertName(reg); c.Name != want {
		return fmt.Errorf("certificate name %q is not stable for its domains: they all belong to %q, "+
			"so the name must be %q; a name that follows the domain set orphans the order URL, "+
			"ARI certID and deployed CertID every time a domain is added or removed",
			c.Name, reg, want)
	}
	return nil
}

// WriteDocument writes the document atomically.
//
// It must write a temp file in the same directory and then rename: wecert may be
// reading at that very moment, and a truncated document looks like "half the
// domains are gone" -- the most dangerous input there is. rename is atomic within
// one filesystem, so a reader sees either the old version or the new one.
func WriteDocument(path string, doc *Document) error {
	if err := doc.Validate(); err != nil {
		return err
	}
	return WriteDocumentUnchecked(path, doc)
}

// WriteDocumentUnchecked is WriteDocument without validation.
//
// Only for the onboarding component where validation would fail and evidence
// must still be left behind (for example reporting a state that "should have been
// generated but was not"). Do not use it to bypass validation.
func WriteDocumentUnchecked(path string, doc *Document) error {
	body, err := yaml.Marshal(doc)
	if err != nil {
		return fmt.Errorf("encode desired-state document: %w", err)
	}

	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".desired-state-*.tmp")
	if err != nil {
		return fmt.Errorf("create temp file in %s: %w", dir, err)
	}
	tmpName := tmp.Name()
	// Every failure path must remove the temp file, or the directory slowly fills
	// with junk.
	defer func() {
		if tmpName != "" {
			_ = os.Remove(tmpName)
		}
	}()

	if _, err := tmp.WriteString(DocumentHeader); err != nil {
		tmp.Close()
		return fmt.Errorf("write document header: %w", err)
	}
	if _, err := tmp.Write(body); err != nil {
		tmp.Close()
		return fmt.Errorf("write document body: %w", err)
	}
	// fsync before rename: otherwise a power loss can leave behind a renamed,
	// zero-byte document whose contents never reached disk.
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return fmt.Errorf("sync document: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close document: %w", err)
	}
	if err := os.Chmod(tmpName, 0o644); err != nil {
		return fmt.Errorf("chmod document: %w", err)
	}

	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("replace %s: %w", path, err)
	}
	tmpName = "" // Already renamed away; do not delete.
	return nil
}
